---
- name: Install docker on dockerbox
  hosts: dockerbox
  vars_files:
    - vars/vault.yml
  roles:
    - role: grog.package
      become: true
      tags:
        - never
        - packages

    - role: systemd
      become: true
      tags:
        - never
        - systemd

    - role: resolveconf
      tags:
        - never
        - resolvconf

    - role: mounts
      tags:
        - never

    - role: geerlingguy.docker
      docker_users:
        - "{{ ansible_user }}"
      become: true
      tags:
        - never
        - install_docker

    - role: install/runitor
      runitor_url: "http://localhost:{{healthchecks.port}}/ping"
      runitor_ping_key: "{{ healthchecks.ping_key }}"
      tags:
        - never
        - install_runitor

    - role: docker-services
      tags:
        - always

    - role: fuzzymistborn.autorestic
      become: true

    - role: cronjobs
