- name: Mount a SMB volume
  become: true
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    opts: "{{ item.opts }}"
    state: "{{ item.state }}"
    fstype: "{{ item.fstype }}"
  loop: "{{ mounts }}"


# - name: Mount a SMB volume
#   become: true
#   ansible.posix.mount:
#     src: //192.168.2.44:/hdd_media
#     path: /mnt/hdd_media
#     opts: username={{ item.username }},password={{ item.password }},rw,uid=1000
#     state: mounted
#     fstype: cifs
#   loop: {{ mounts.items }}
