services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - "{{homepage.port}}:3000"
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
    restart: unless-stopped
      