

cronjobs:
  - name: Run Renovate Bot every 2 hours
    job: /usr/local/bin/runitor -slug renovate-bot -- docker compose --file ~/services/renovate/docker-compose.yml up
    user: "{{ ansible_user }}"
    hour: "*/2"
    minute: 0
  - name: Run Firefly automations at 2 am
    job: /usr/local/bin/runitor -slug firefly-automations -- wget -qO- http://localhost:{{firefly.port}}/api/v1/cron/{{firefly.cron_token}}
    user: "{{ ansible_user }}"
    hour: 2
    minute: 0
  - name: Run Firefly backup at 3 am
    job: /usr/local/bin/runitor -slug firefly-backup -- ~/services/firefly/run_backup.sh
    user: "{{ ansible_user }}"
    hour: 3
    minute: 0

package_list:
  - name: cifs-utils


mounts:
  - src: //{{omv.hostname}}/hdd_media
    path: /mnt/hdd_media
    opts: username={{ omv.username }},password={{ omv.password }},rw,uid=1000,noauto,x-systemd.automount
    state: mounted
    fstype: cifs

autorestic_config_user: "{{ ansible_user }}"
autorestic_user_directory: "/home/{{ ansible_user}}"
autorestic_run_check: false
autorestic_config_yaml:
  version: 2
  backends:
    remote:
      type: b2
      key: "{{restic.repo_key}}"
      path: '{{backblaze.bucket}}:dockerbox/services'
      env:
        B2_ACCOUNT_ID: "{{backblaze.applicationid}}"
        B2_ACCOUNT_KEY: "{{backblaze.applicationkey}}"

  locations:
    docker:
      from: '/apps/docker/'
      to:
        - remote
      options:
        backup:
          exclude:
            - 'metube'
        forget:
          keep-daily: 1
          keep-weekly: 8
          keep-monthly: 4
