

cronjobs:
  - name: Run Renovate Bot every 2 hours
    job: /usr/local/bin/runitor -slug renovate-bot -- docker compose --file ~/services/renovate/docker-compose.yml up
    user: "{{ ansible_user }}"
    hour: "*/2"
    minute: 0
  - name: Run Firefly automations at 2 am
    job: /usr/local/bin/runitor -slug firefly-automations -- wget -qO- http://localhost:{{firefly.port}}/api/v1/cron/{{firefly.cron_token}}
    user: "{{ ansible_user }}"
    hour: 2
    minute: 0
  - name: Run Firefly backup at 3 am
    job: /usr/local/bin/runitor -slug firefly-backup -- ~/services/firefly/run_backup.sh
    user: "{{ ansible_user }}"
    hour: 3
    minute: 0

package_list:
  - name: cifs-utils


mounts:
  - src: //{{omv.hostname}}/hdd_media
    path: /mnt/hdd_media
    opts: username={{ omv.username }},password={{ omv.password }},rw,uid=1000
    state: mounted
    fstype: cifs
